# Generated by Django 3.0.14 on 2021-05-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='visite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
