# Generated by Django 3.0.14 on 2021-05-31 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210531_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='visite',
            new_name='visits',
        ),
    ]
